### ISSUE TITLE
Leap Hands Appear Warped

### ISSUE THREAD

**Issue by AlexE89** [leapmotion/LeapIPC#2]
![leaphand_screenshot2](https://cloud.githubusercontent.com/assets/18400245/14431697/d5673cb6-ffd4-11e5-9aae-b460b697e3a4.PNG)
![leaphand_screenshot](https://cloud.githubusercontent.com/assets/18400245/14431255/d4952bec-ffd2-11e5-829f-5c9cd44b89ef.PNG)

Hello,

I downloaded the "Leapmotion_Basehand_Rig_Left.fbx" to test it in Unity. For some reason, this hand model as well as several others that I have tried become warped during run time (see screenshot). In addition to being warped, I noticed that the RigidHand model (included with the Leap SDK) is not properly aligned with the hand. I suspect this is at least part of the problem, but even if it is I'm not sure what to do about it.

For this particular model, I downloaded it and imported directly to Unity. Other hand models I have tried, I have opened in 3ds max and exported from there.

If anyone has any advice on how to fix this issue I would greatly appreciate it. I'm not sure if there are any particular settings that I need to check in Unity and/or 3ds max.

Thank you,
Alex

**Comment by jdonald** [comment]
Hi @AlexE89 I'm sorry that was never replied to since April, although I do recall someone mentioning an odd issue got filed in LeapIPC. LeapIPC is one of many leapmotion public repositories and only covers code for our interprocess communication transport.

Did you get directed to other channels to ask your question. Perhaps the appropriate github repo https://github.com/leapmotion/UnityModules where you could have filed a similar issue?

Our Unity assets have been continually evolving, so perhaps was resolved at some point a while back?
